# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20170608_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='date published')),
                ('hora_salida', models.TimeField()),
                ('hora_llegada', models.TimeField()),
                ('hora_embarque', models.TimeField()),
                ('numero_embarque', models.CharField(max_length=20)),
                ('precio', models.IntegerField(default=0)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_of', to='flights.Aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Aeropuerto')),
            ],
        ),
    ]
