# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_aeropuerto_vuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_cliente',
            fields=[
                ('numero_ticket', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ci', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('asiento', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='fecha',
            field=models.DateTimeField(verbose_name='Salida'),
        ),
        migrations.AddField(
            model_name='ticket_cliente',
            name='vuelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.Vuelo'),
        ),
    ]
